import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Layout from "@/components/layout";
import Ninja from "../../public/images/ninja.png";
import AnimatedText from "@/components/AnimatedText";
import {motion} from "framer-motion";
import Link from "next/link";
import {LinkArrow} from "@/components/icon";
import CtaButton from "@/components/CtaButton";

const description = {
    initial: {
        y: 70,
        opacity: 0,
    },
    animate: {
        opacity: 1,
        y: 0,
        transition: {
            delay: 0.3,
            duration: 0.6,
        }
    }
}
const image = {
    initial: {
        x: -70,
        opacity: 0,
    },
    animate: {
        opacity: 1,
        x: 0,
        transition: {
            delay: 0.3,
        }
    }
}
export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <main className="flex items-center text-dark w-full min-h-screen">
                <Layout className="pt-0">
                    <div className="flex items-center justify-between w-full">
                        <div className="w-1/2">
                            <Image variants={image} initial="initial" animate="animate"
                                   src={Ninja} alt="kmpr" className="w-full h-auto"/>
                        </div>
                        <div className="w-1/2">
                            <AnimatedText text="KMPR" className="!text-6xl !text-left"/>
                            <motion.p className="my-4 text-base font-medium"
                                      variants={description} initial="initial" animate="animate"
                            >As a skilled full-stack developer, I am dedicated to turning ideas into innovative web
                                applications.
                                Explore my latest projects and articles, showcasing my expertise in React.js and web
                                development.
                            </motion.p>
                            <div className="flex gap-3 items-center">
                                <Link target={"_blank"} href="/dummy.pdf" download={true}
                                      className="flex items-center bg-primary text-light p-2.5 px-6 rounded-lg text-lh font-semibold border-solid border-2 border-transparent hover:bg-transparent hover:border-primary hover:text-primary">
                                    Resume <LinkArrow className={'w-6'}/>
                                </Link>
                                <Link className="text-lg font-medium capitalize text-primary underline" target={"_blank"} href="mailto:korosh.mpr@gmail.com">Contact</Link>
                            </div>
                        </div>
                    </div>
                    <CtaButton />
                </Layout>
            </main>
        </>
    )
}
